name: Publish Docker image 

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout respository
      uses: actions/checkout@v3
            
    - name: Login to dockerhub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push docker image
      run: |  
        docker build -f adamohlson1/gruppuppgift .
        docker push adamohlson1/gruppuppgift