name: Publish Docker image 

on:
  push:
    branches:
    - '*'
  pull_request:
    branches: 
    - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Checkout respository
      uses: actions/checkout@v2
            
    - name: Set up .net
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore and build
      run: |
        dotnet restore
        dotnet build
    
    - name: Test
      run: dotnet test --configuration Release --no-restore
    - name: Restore and build
      run: |
        dotnet restore
        dotnet build


##    - name: Login to dockerhub
##      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          
##    - name: Build and push docker image
##      run: |  
##        docker build -f adamohlson1/gruppuppgift .
##        docker push adamohlson1/ 
